INSERT INTO maps (user_id, map_lng, map_lat, map_title, map_pic_url,map_description)
VALUES
( 1,49.28249, -123.127576, 'Great Food Spots',
'https://www.thebalancesmb.com/thmb/kectf9d4azgI8yVnBuoB0h2Z8zA=/3865x2174/smart/filters:no_upscale()/overhead-view-of-smiling-female-friends-sharing-lunch-in-restaurant-928010348-5b4abe8f46e0fb003712c478.jpg', 'All my favourite places to eat in downtown Vancouver! Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris congue metus id sapien mollis pulvinar. Phasellus aliquet vitae dolor ac congue. Aenean aliquet accumsan iaculis. Nulla elementum malesuada consequat. Pellentesque et consectetur enim, pharetra laoreet lacus. Suspendisse mattis nunc at elit tristique, et accumsan erat suscipit. Vivamus ornare interdum enim, id faucibus arcu accumsan vitae. Nam elementum eu diam ut posuere. Nam placerat quam vitae mi sagittis condimentum.'),
( 2,49.28249, -123.127576,'Great Beer Spots ',
'https://images.adsttc.com/media/images/5782/73cf/e58e/ce07/9c00/0039/large_jpg/LATITUDE-DONGLI-BREWERY-01_dining_area.jpg?1468167055', 'All my favourite places to drink beer in downtown Vancouver! Ut quis augue id diam aliquam congue ut id ligula. Quisque vel fringilla elit. Sed sagittis, lacus sed porttitor pretium, tellus neque volutpat mi, sit amet vestibulum lorem libero in risus. Curabitur eget tellus ligula. Mauris vel lacus tristique massa congue porttitor non posuere risus. Suspendisse potenti. Nulla mollis fringilla purus et interdum. Aenean tristique erat id ex consequat, vitae tempor purus posuere. Nulla ornare blandit odio, non pharetra metus imperdiet id. Ut quis lacus blandit, tempus urna at, blandit elit. Quisque placerat orci facilisis erat tempus dictum.'),
( 3,49.28249, -123.127576,'Great Hiking Spots',
'https://www.rei.com/dam/parrish_091412_0679_main_lg.jpg', 'Great hikes within an hour of downtown. Vestibulum eros diam, rhoncus a ex in, egestas mattis turpis. Curabitur non augue et ex semper cursus dictum vel leo. Integer maximus, mi nec efficitur iaculis, mauris mi porttitor lorem, quis bibendum arcu quam eu dolor. Donec eu tincidunt tortor, a blandit mi. Duis luctus, tellus id elementum euismod, ante quam mollis tellus, ut ultrices sapien leo quis justo. Proin efficitur mi ac massa rhoncus, eu semper leo iaculis. Pellentesque porta varius quam eu tempus. Mauris gravida lobortis tortor non ornare. '),
( 4,49.28249, -123.127576,'Great Ice Cream Spots',
'https://st2.depositphotos.com/1785712/7320/i/950/depositphotos_73205765-stock-photo-display-window-of-assorted-ice.jpg', 'Where to get the best ice cream in town! Nullam mollis, diam ac pulvinar egestas, lacus urna faucibus velit, quis dictum odio nisl sit amet ligula. Fusce a varius quam, mattis posuere eros. Phasellus posuere consequat dolor, convallis vestibulum lorem accumsan et. Maecenas purus neque, sollicitudin vitae molestie a, molestie suscipit ipsum. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Cras eget malesuada velit. Donec enim enim, venenatis eu nunc sodales, rutrum malesuada sem. Sed ut tortor porttitor, tincidunt orci pharetra, consequat tellus. Praesent ornare eget nibh rhoncus interdum. Vivamus eu nisl ligula. '),
( 1,49.28249, -123.127576,'Great Nightclubs',
'https://upload.wikimedia.org/wikipedia/commons/3/32/Wikipedia_space_ibiza%2803%29.jpg', 'The best nightclubs in town! Praesent a nisl enim. Nullam aliquam quam eu gravida viverra. Phasellus pretium odio ut mauris varius ultrices. Proin dictum at erat in tincidunt. Nullam interdum purus sed pharetra mattis. Sed nec quam interdum est iaculis porttitor. Integer ac rhoncus odio. Fusce dictum ornare justo, nec pellentesque nunc consectetur a. Phasellus eu nulla mattis, pharetra quam a, dapibus ex. Donec id dui quis metus blandit fringilla. Etiam dapibus mauris vel arcu tincidunt sodales. Quisque at iaculis odio, ultricies aliquet massa.'),
( 2,49.027296, -125.665175,'Great Surfing Spots',
'https://i.huffpost.com/gen/2111260/thumbs/o-EARLY-MORNING-SURFING-570.jpg?1', 'Best spots to surf! Vestibulum eros diam, rhoncus a ex in, egestas mattis turpis. Curabitur non augue et ex semper cursus dictum vel leo. Integer maximus, mi nec efficitur iaculis, mauris mi porttitor lorem, quis bibendum arcu quam eu dolor. Donec eu tincidunt tortor, a blandit mi. Duis luctus, tellus id elementum euismod, ante quam mollis tellus, ut ultrices sapien leo quis justo. Proin efficitur mi ac massa rhoncus, eu semper leo iaculis. Pellentesque porta varius quam eu tempus. Mauris gravida lobortis tortor non ornare.'),
(1, 49.16006168907257, -122.92067308113413, 'Pokémon Go Spots', 'https://static01.nyt.com/images/2020/01/21/multimedia/31xp-pokemongo/21xp-pokemongo-videoSixteenByNineJumbo1600.jpg','I want to be the very best Like no one ever was To catch them is my real test To train them is my cause I will travel across the land Searching far and wide Each Pokemon to understand The power thats inside Pokemon! Gotta catch em all Its you and me I know its my destiny Pokemon! Oh, youre my best friend In a world we must defend Pokemon! Gotta catch em all A heart so true Our courage will pull us through You teach me and Ill teach you Pokemon! Gotta catch em all Gotta catch em all Every challenge along the way With courage I will face I will battle everyday.'),
(2, 48.86113751762755, 2.3359018005430703, 'Vacation Plan', 'https://images.unsplash.com/photo-1551634979-2b11f8c946fe?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTJ8fHBhcmlzfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=800&q=60', 'Ouais comme même ouais deux boulangerie me car du passer épicé. Omelette du coup à grève très car savoir ouais bière sans parce que vin du. Me grève manger. Parce que putain car vin. Ouais deux dans l cul point putain putain. Croissant évidemment je fromage apéro pas putain guillotine demander et aussi. Vin comme même épicé et aussi. ' );
