DROP TABLE IF EXISTS maps CASCADE;

CREATE TABLE maps (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  title VARCHAR(255) NOT NULL,
  lat numeric NOT NULL,
  lng numeric NOT NULL,
  zoom smallint NOT NULL DEFAULT 13,
  created_on TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
  active  BOOLEAN NOT NULL DEFAULT TRUE
);
